### ISSUE TITLE
Unable to close db- failed to enable constraints

### ISSUE THREAD

**Issue by cmatthew11** [EnergyExemplarNorthAmerica/Python-PLEXOS-API#16]
I am editing a file using the API which all seems to be fine, but when I go to save the file with "db.Close()" it gives the below error. Can anyone help troubleshoot what the constaints that aren't being enabled are and how to identify them? Thanks

IOException: PLEXOS API Error:	Error saving the input datafile to C:\Users\Chris\Desktop\Coding\Python\PLEXOS\PLEXOS API\1.elec_model\1.elec_model.xml
Failed to enable constraints. One or more rows contain values violating non-null, unique, or foreign-key constraints.
   at PLEXOS_NET.Core.Base.ThrowError(String strException, Exception ex)
   at PLEXOS_NET.Core.Connection.CloseConnection(ConnectionType DataType)
   at PLEXOS_NET.Core.DatabaseCore.Close()

**Comment by sebroad** [comment]
Hello

This error may indicate that you have added a duplicate property row which
is not tagged with a scenario. If two rows have the same parent object,
child object, property, date from, date to, pattern and scenario, this kind
of error can arise.

**Comment by cmatthew11** [comment]
OK great thanks, you're absolutely right the error was due to duplicate properties
